#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: theophane-droid
  description: A beautiful lab builder
  company: The fictive ( but not unreal ) deemel company
  license: license touche pas à ça
  min_ansible_version: 2.1
  galaxy_tags: []
dependencies: []
